# Generated by Django 5.0.6 on 2024-07-07 16:30

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgId', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix='', unique=True)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
            ],
        ),
    ]
